### ISSUE TITLE
Specifying target of Global results in error.

### ISSUE THREAD

**Issue by wallabyies** [wks-sumo-logic/sumologic-backup#1]
When I run this command:

```
python3 sumologic_backup.py -c sumologic-backup.initial.cfg -t Global -o backups -z sumo-backup.zip
```

I receive this error:

```
Traceback (most recent call last):
  File "sumologic_backup.py", line 516, in <module>
Step-001: - Authenticating
Step-002: - Creating Supporting directories
Step-003: - Discovering content targets
    main()
  File "sumologic_backup.py", line 342, in main
    _content_manifest = create_content_map(source)
  File "sumologic_backup.py", line 250, in create_content_map
    uid_parent = content_list['parentId']
KeyError: 'parentId'
```

- Personal backup works fine.   Only a Global target fails.
- User account has Administrator rights in Sumo and can view all searches.

**Comment by wks-sumo-logic** [comment]
Many thanks for the report! I found the issue, and have refactored the Global folder and it looks to be working correctly.

The root cause was in the logic. 

When we get a Global folder, we have to kick off a job to collect all of the content we have access to.
I mistakenly thought the job ID was the content ID. This has been fixed!

Please try out the code now and many thanks for your patience!

**Comment by wallabyies** [comment]
I confirmed this fixed the issue, thank you!
